<?php $this->layout()->pageTitle = "Rob's Blog &raquo; About"; ?>

<?php
$this->crumbContainer(array(
    'label' => 'about',
    'uri' => '#',
    'active' => true
));
?>

<h3>The Site</h3>
<p>
    I've parked this area on the world wide web as a spot where I can both share things that I've learned, and also experiment with technologies that I'm interested in; namely web development related. To watch the code behind the site grow, and to see how I've implemented some things, check out what's <a title="behind the site" href="http://github.com/rkeplin/Blog">behind the site</a>.
</p>