<?php $this->layout()->pageTitle = 'Rob\'s Blog &raquo; ' . 'Categories' . ' &raquo; ' . $this->category->getName(); ?>

<?php
$this->crumbContainer(array(
    'label' => 'categories',
    'uri' => $this->myUrl('blog/default', array('controller' => 'category', 'action' => 'view')),
    'pages' => array(
        array(
            'label' => strtolower($this->category->getName()),
            'uri' => '#',
            'active' => true
        )
    )
));
?>

<div class="post">
    <h1><?php echo $this->category->getName(); ?></h1>
    <?php if(count($this->posts) > 0) : ?>
    <ul class="latest-blogs">
    <?php foreach($this->posts as $post) : ?>
        <li><a title="<?php echo $post->getTitle(); ?>" href="<?php echo $this->myUrl('blog/default/query', array('action' => 'view', 'category' => urlencode($post->getCategory()->getName()), 'title' => urlencode($post->getTitle()))) ?>"><?php echo $post->getTitle() ?></a></li>
    <?php endforeach; ?>
    </ul>

    <?php echo $this->paginationControl($this->posts, null, 'pagination.phtml', array('route' => 'blog/default/query', 'controller' => 'category', 'action' => 'blogs')) ?>

    <?php else : ?>
        There are no posts in the category <strong><?php $this->getCategory() ?></strong>.
    <?php endif; ?>
</div>