<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'blog/about/index'    => __DIR__ . '/view/blog/about/index.phtml',
    'blog/archive/blogs'  => __DIR__ . '/view/blog/archive/blogs.phtml',
    'blog/archive/view'   => __DIR__ . '/view/blog/archive/view.phtml',
    'blog/blog/create'    => __DIR__ . '/view/blog/blog/create.phtml',
    'blog/blog/edit'      => __DIR__ . '/view/blog/blog/edit.phtml',
    'blog/blog/latest'    => __DIR__ . '/view/blog/blog/latest.phtml',
    'blog/blog/view-all'  => __DIR__ . '/view/blog/blog/view-all.phtml',
    'blog/blog/view'      => __DIR__ . '/view/blog/blog/view.phtml',
    'blog/category/blogs' => __DIR__ . '/view/blog/category/blogs.phtml',
    'blog/category/view'  => __DIR__ . '/view/blog/category/view.phtml',
    'blog/comment/view'   => __DIR__ . '/view/blog/comment/view.phtml',
    'blog/contact/index'  => __DIR__ . '/view/blog/contact/index.phtml',
    'blog/user/login'     => __DIR__ . '/view/blog/user/login.phtml',
    'blog/search/index'   => __DIR__ . '/view/blog/search/index.phtml',
    'layout/layout'       => __DIR__ . '/view/layout/layout.phtml',
    'pagination'          => __DIR__ . '/view/partials/pagination.phtml', //This doesn't work.
    'error/404'           => __DIR__ . '/view/error/404.phtml',
    'error/index'         => __DIR__ . '/view/error/index.phtml',
);